### PR TITLE
fix: better detection of references, handle namespace dependencies

### LINKED ISSUE #86: dts-buddy 0.5.1 generating `error_1` instead of `error`
See https://github.com/sveltejs/kit/pull/12377. It's generating `error_1` instead of `error`, which is causing the site build to fail. It's aliased as `error` when exported, but it'd be nice to just have it be called `error` in the first place

### LINKED ISSUE #88: namespaces are not traversed
When you have a namespace with declarations inside which reference imports, those imports are not marked as used and subsequently removed. Looking at the code there just seems no logic whatsoever to traverse namespaces in that regard.

### PR DESCRIPTION
**Pull request by dummdidumm**
- fixes #86: tweak the "is this a reference logic" to not care about method signatures, and not care about the sub parts of qualified names (i.e. we only care about X in a `X.Y.Z` type reference, because we don't traverse into namespaces, and this can only be a namespace reference)
- fixes #88: add the dependencies of namespaces to the namespace declaration, or else treeshaking would wrongfully remove imports that are only dependencies of the declarations _inside_ the namespace
- also fixes `import * as X` namespace imports, they were not handled correctly before (a bit unrelated to this PR, but I came across it while investigating the whole namespace thing)

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -523,23 +553,25 @@ export function is_declaration(node) {
...
  */
-export function is_reference(node) {
+export function is_reference(node, include_declarations = false) {
 	if (!ts.isIdentifier(node)) return false;
 
 	if (node.parent) {
 		if (is_declaration(node.parent)) {
 			if (ts.isVariableStatement(node.parent)) {
-				return node === node.parent.declarationList.declarations[0].name;
+				return false;
```
Comment (dummdidumm) [inline src/utils.js:565]: I changed this because the previous statement didn't make sense - the node could never be equal to the right hand side, because the node itself can only ever be `VariableDeclarationList`

**Comment by dummdidumm** [comment]
(side note: I recommend changing the default from `Merge pull request` to `Squash and merge`)
